blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/GizzZmo/Ai_shell/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/GizzZmo/Ai_shell/blob/main/README.md
    about: Check the documentation for answers to common questions